# Generated by Django 5.2.17 on 2026-10-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_app_rating_app_rating_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='rating',
            new_name='rating_avg',
        ),
    ]
